services:
  app:
    container_name: tls_app
    build:
      dockerfile: dockerfile
      context: .
      network: host
    command: ["python3", "src/__init__.py"]
    restart: always
    ports:
      - 6000:6000
    volumes:
      type: bind
      source: ./src/uploads
      target: /app/src/uploads

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: