services:
  app:
    container_name: tls_app
    build:
      dockerfile: dockerfile
      context: .
    command: ["python3", "src/__init__.py"]
    restart: always
    ports:
      - 5000:5000
    network_mode: host

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    network_mode: host

volumes:
  mongo-data: