services:
  app:
    container_name: tls_app
    build:
      dockerfile: dockerfile
      context: .
    command: ["python3", "src/__init__.py"]
    restart: always
    ports:
      - 5000:5000
  
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: