services:
  app:
    container_name: tls_app
    network_mode: host
    build:
      dockerfile: dockerfile
      context: .
      network: host
    command: ["python3", "src/__init__.py"]
    restart: always
    ports:
      - 6000:6000

  mongo:
    image: mongo
    network_mode: host
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: